### ISSUE TITLE
Using Benchmarkjs with Webpack + Babel

### ISSUE THREAD

**Issue by bunkat** [bestiejs/benchmark.js#106]
Hi,

I'm trying to incorporate Benchmarkjs into my workflow but it looks like it does something funny with require which is preventing it from working correctly (see http://stackoverflow.com/questions/32242072/using-benchmarkjs-with-webpack-and-babel).  Basically I'm trying to transpile my code from es6 to es5 and then pack the benchmarks using webpack before executing them from an npm script.

Is there a way currently to get Benchmarkjs working in this configuration?  Is there a way to at least be able to execute benchmarks using es6?

**Comment by SharpEdgeMarshall** [comment]
:+1:

**Comment by ctumolosus** [comment]
I ran into the same issue, but I was able to run the benchmarks even with warnings and errors being logged on the terminal. To suppress them I configured webpack to avoid parsing benchmarks.js when resolved. I don't think is ideal but it seems to work fine so far.

```js
    module: {
        noParse: [
            // Suppress warnings and errors logged by benchmark.js when bundled using webpack.
            // https://github.com/bestiejs/benchmark.js/issues/106
            path.resolve(__dirname, './node_modules/benchmark/benchmark.js')
        ],
        loaders: [{
            test: /\.(jsx|es6)$/,
            loader: 'babel',
            exclude: /node_modules/,
            query: { optional: ['runtime'] }
        }, {
            test: /\.json$/,
            loader: 'json'
        }]
    },
```

**Comment by listepo** [comment]
+1

**Comment by jdalton** [comment]
Moved to #128.
