### ISSUE TITLE
Cannot require json files in node

### ISSUE THREAD

**Issue by creynders** [bestiejs/benchmark.js#108]
If you try to require a json file in a node file which sets up Benchmark, it will resolve to an empty object, w/o warning or error. (Running benchmark.js from master branch BTW)
Is this fiddling with the `require` function really necessary? IMO it's _really_ REALLY bad practice to mess around with built-in objects, functions etc. Wouldn't it be an option to create a node-specific version or so, which just doesn't fuck around with any of the core stuff? Took a glance at the code and it seems to me that would be pretty feasible.

**Comment by jdalton** [comment]
Benchmark.js doesn't fiddle with the `require` function.

**Comment by creynders** [comment]
Ah, holy crap, you're right. My sincere apologies. Turns out there's a bug in node.js with json files having a `JSON` extension (instead of `json`)

**Comment by jdalton** [comment]
No worries :D
