### ISSUE TITLE
Infinity operations coming back under IE and Edge occasionally

### ISSUE THREAD

**Issue by kpdecker** [bestiejs/benchmark.js#109]
Occasionally will see `Infinity` coming back in the `result` field on IE and Edge when testing six-speed. Worked around this with a [retry](https://github.com/kpdecker/six-speed/commit/6ddc5727f7809a11b18fabd665684e24f33c1f61) but this feels like the wrong thing to do when trying to examine performance numbers.

**Comment by jdalton** [comment]
We [have measures](https://github.com/bestiejs/benchmark.js/blob/8c2b72a98945035e5c43e57da3b29185a0462cb1/benchmark.js#L60-L67) in place to reduce the occurrence of `Infinity` hz. That said it can happen from time to time if what you're measuring is very very fast. It is a good indicator that either a bad test run has occurred or what you're measuring is really nano.

**Comment by kpdecker** [comment]
These are microtests so yes they are quite fast in execution. I'll update six-speed to use the nano timers where possible and that will hopefully mitigate some as well as increase data fidelity. Sorry for filing what was basically a support issue.

**Comment by jdalton** [comment]
Benchmark.js will auto detect and use [node-microtime](https://github.com/wadey/node-microtime) if you install it as part of your other deps.

**Comment by kpdecker** [comment]
Haven't had any problems with the other runtimes, just IE and Edge. For the former could eventually get the applet running with a number of installs and permissions checks but frankly it doesn't seem worth the cost since it's a dead product. The later doesn't support plugins according to an error I saw when trying to setup VM.

Looks like stuck with the restart solution unless Edge adds one of the non-java high fidelity timer options in the future.

**Comment by jdalton** [comment]
I'll re-evaluate the use of `performance.now` to help with this.
