### ISSUE TITLE
Benchmark.Suite is undefined in version 2.0.0

### ISSUE THREAD

**Issue by wrumsby** [bestiejs/benchmark.js#113]
Using version 2.0.0 via Bower and as per the documentation and README I tried to create a suite like this:

```js
var suite = new Benchmark.Suite;
```

That failed and looking in the Chrome dev tools there's no autocompletion for `Benchmark.Suite` and `Benchmark.Suite` is `undefined`.

If I change the version of benchmark in my `bower.json` to `^1.0.0` and re-install the above works.

**Comment by jdalton** [comment]
Benchmark.js v2 pulled bower support. But beyond that you'll need to have lodash loaded first because it's a hard dependency.

**Comment by jdalton** [comment]
You can verify [here](https://output.jsbin.com/qicaza/1/) that `Benchmark.Suite` exists. If you remove the `lodash` dep you can verify that `Benchmark.Suite` is missing.
