### ISSUE TITLE
Are setup/teardown called each time function executes or only once per loop?

### ISSUE THREAD

**Issue by adrian-moisa** [bestiejs/benchmark.js#115]
I'm trying to get a proper measurement for this setup:

	// 20.000 ops/sec
	suite.add('_setupListeners(); _removeListeners();', {
        fn: function () {
            inputs._setupListeners();
            inputs._removeListeners();
        }
    });

	// 114.000 ops/sec
    suite.add('_setupListeners(); - Teardown removeListeners()', {
        fn: function () {
            g_inputs._setupListeners();
        },
        teardown: function () {
            g_inputs._removeListeners();
        }
    });

    // I get around 560.000.000 ops/sec for the most basic 
    // operations on this machine (addition, ifs, etc). 
    // Usually it's 5 to 60 million for regular stuff.

I am deducing that the second test cannot measure correctly the time it takes to setup listeners. It think this happens because, at first step in the loop, listeners are set up and then the next itersations don't add to much overhead because the browser checks that it allready has the listeners in place and skips over the whole process.

Is there anyway I can force the browser to take the long trip of setting up the listeners at each step of the loop? I mean, is it possible to benchmark `setupListeners()` and `removeListeners()` separately?

**Comment by jdalton** [comment]
Setup and teardown are per sample. A test is sampled as many times as possible in 5 seconds (by default). A sample consists of a test loop which executes as many times as needed to get an accurate measurement (usually 50 milliseconds). This could result in thousands or millions of executions.

Long setups can bog things down so you'll want to balance it a bit. The flow of each sample looks something like
```
<setup>
<clock start>
for (i=0; i < someCount; i++) {
  <test>
}
<clock stop>
<teardown>
```

You can access the iteration count, `someCount`, by `this.count` if you want to know how many items to setup or teardown.

It's a balance and some tests may not be compatible with benchmark.js' approach.

**Comment by adrian-moisa** [comment]
Thank you! This clarifies a lot!
