### ISSUE TITLE
Mochalike usage?

### ISSUE THREAD

**Issue by calebmer** [bestiejs/benchmark.js#117]
Is there any easy to use mochalike command line interface? I'd like to use `$ benchmark` in bash and have it run all the benchmarks in a `benchmark` directory.

**Comment by KrisSiegel** [comment]
While there isn't an easy way to do this out of the box I currently do this in my [msngr.js](https://github.com/KrisSiegel/msngr.jsl) repository. Essentially anything that is a benchmark ends up ```*.bench.js```. Then I have a grunt task that gathers up all of these files, writes them into HTML files (so I can run them in a browser context) then automatically executes each one, serially, in node.

**Comment by jdalton** [comment]
@KrisSiegel Nice!
