### ISSUE TITLE
Fix continuous integration builds

### ISSUE THREAD

**Issue by mathiasbynens** [bestiejs/benchmark.js#118]
Builds have been failing ever since commit 0174dfc105c64435947d59f60e25b4f0095d6689 — not sure what’s up. https://travis-ci.org/bestiejs/benchmark.js/jobs/105122530

**Comment by mathiasbynens** [comment]
Uh-oh — even local builds are failing:

```sh
$ node test/test.js
----------------------------------------
Benchmark.Suite filtered results onComplete
----------------------------------------
 FAIL - should filter by fastest
    FAIL | EQ | ok | Expected: a, Actual: c
 FAIL - should filter by successful
    FAIL | EQ | ok | Expected: a, Actual: c
    FAIL | EQ | ok | Expected: a,b, Actual: a,b,c
----------------------------------------
    PASS: 183  FAIL: 2  TOTAL: 185
    Finished in 80542 milliseconds.
----------------------------------------
```

**Comment by mathiasbynens** [comment]
@jdalton Do you know more? Something about the Lo-Dash v4 update broke the tests.

**Comment by jdalton** [comment]
Yep. I see the fails (which is why I removed the tag). I'm not sure what is causing it as I had code to juggle both (I was using a 4.0-pre locally for a while).

**Comment by jdalton** [comment]
I ran `lodash-migrate` and narrowed it down to `_.assign` results. Will dig in tonight.

**Comment by jdalton** [comment]
Fixed https://github.com/bestiejs/benchmark.js/commit/0c7323f4dffd5f8c348c731bc8ccd66ab7adbae2.

**Comment by mathiasbynens** [comment]
Thanks! :+1:
