### ISSUE TITLE
Benchmark.Suite setup/teardown ?

### ISSUE THREAD

**Issue by jeromeetienne** [bestiejs/benchmark.js#12]
is there a setup/teardown mechanism at the suite level ?

i looked and didnt see it

**Comment by dkaraush** [comment]
Still not available?

**Comment by dkaraush** [comment]
Still not available? I didn't find it in documentation. :(

**Comment by jdalton** [comment]
> Still not available?

Still waiting on a PR :)

**Comment by rapodaca** [comment]
How about a statement of best practices when using Suite?

The home page gives a Suite example, but no clear way (even a workaround) for setting up the Suite. Setup seems like a critical piece of functionality, so it seems like I'm missing something obvious.

How does one go about setting up a benchmark Suite so as to avoid biasing the results with the setup code?
