### ISSUE TITLE
Unable to specify run count

### ISSUE THREAD

**Issue by Jameskmonger** [bestiejs/benchmark.js#121]
Hi benchmark team,

When I run a benchmark with the following options:

    .run({
        async: true
    });

I get the following outputs:

    ... (73 runs sampled)
    ... (76 runs sampled)
    ... (78 runs sampled)

So when I add a `minSamples` setting to the `run` call, like so:

    .run({
        async: true,
        minSamples: 25000
    });

I get the following outputs:

    ... (67 runs sampled)
    ... (78 runs sampled)
    ... (77 runs sampled)

The `minSamples` setting doesn't actually seem to change the amount of runs sampled in the Benchmark.

Am I doing something wrong?

**Comment by jdalton** [comment]
Have you tried the latest version (2.1.0). I'm not able to repro.
