### ISSUE TITLE
Recovering from errors in deferred benchmarks

### ISSUE THREAD

**Issue by kevinoid** [bestiejs/benchmark.js#123]
Is there a way to detect errors in a deferred benchmark and continue to run any other benchmarks in the suite?  Since the [pretest error checks are skipped for deferred benchmarks](https://github.com/bestiejs/benchmark.js/blob/2.1.0/benchmark.js#L1601) and there doesn't appear to be any global error handler, I assume Benchmark.js does not do this automatically.  The benchmark also doesn't appear to have a timeout, instead node just exits after an error due to an empty event loop.

The best I could come up for doing this from the calling code was something like the following:

```js
var Benchmark = require('benchmark');
var suite = new Benchmark.Suite();
suite
  .add('broken', function(deferred) { throw new Error('nope'); }, {defer: true})
  .add('ok', function() { 'Hello World!'.indexOf('o') > -1; })
  .on('abort', function() { console.log('suite aborted'); })
  .on('cycle', function(evt) { console.log(String(evt.target)); })
  .on('error', function(evt) { console.log('suite error', evt.target.error); });

var currentBenchmark;
function handleBenchmarkError(err) {
  // Set the error property of the benchmark, as the internals would do
  currentBenchmark.error = err;
  // Abort the current benchmark (doesn't abort the suite)
  currentBenchmark.abort();
}
suite.forEach(function(bench) {
  bench
    .on('start', function() {
      currentBenchmark = this;
      process.once('uncaughtException', handleBenchmarkError);
    })
    .on('complete', function() {
      process.removeListener('uncaughtException', handleBenchmarkError);
      currentBenchmark = null;
    });
});

suite.run();
```

This seems like a step in the right direction, but `.abort()` doesn't appear resume the suite (or emit `'abort'` or `'error'`) and assigning to `.error` is a bit hacky.  I did find a really hacky way to do it by exporting `deferred` from the benchmark setup into the global scope so that `deferred.resolve()` could be called after `.abort()`.  That works, but it's obviously a total hack.

Is there a way to abort and/or recover from errors in deferred benchmarks?

**Comment by jdalton** [comment]
I think what you've got is a good start. I'm not so concerned with the error case as most should be benchmarking working code.

**Comment by kevinoid** [comment]
Fair enough.  I made [a gist of the code that I'm currently using](https://gist.github.com/kevinoid/8278d3d27f409932a967) for others who may encounter this issue.  It works fine for me.  Feel free to suggest improvements.
