### ISSUE TITLE
Suite.prototype.{add,on,off} return values

### ISSUE THREAD

**Issue by BenoitZugmeyer** [bestiejs/benchmark.js#124]
The [documentation](https://benchmarkjs.com/docs#Suite_prototype_add) tells `Suite.prototype.add` returns the benchmark instance, but in reality it returns the suite instance. I'd make a PR but I don't know what is expected here, fix the doc or the return value.

Same goes for `on` and `off`.

**Comment by jdalton** [comment]
It's supposed to return the suite to allow chaining method calls. For the PR you can just modify the benchmark.js jsdoc source. Thanks @BenoitZugmeyer!
