### ISSUE TITLE
matcha; benchmark definition

### ISSUE THREAD

**Issue by fanatid** [bestiejs/benchmark.js#127]
I opened [matcha](https://github.com/logicalparadox/matcha) today for myself and found that benchmark definition there is very very nice.

What you think about package based on benchmark.js for simple benchmarks with similar definition, like:
```js
var b = require('some-new-package-name')

b.suite((b) => {
  before(() => console.log('before'))
  after(() => console.log('after'))
  beforeEach(() => console.log('beforeEach'))
  afterEach(() => console.log('afterEach'))

  b.bench('add#1', () => {
    let x = 4 + 2
  })

  b.bench('add#2', (done) => {
    let x = 4 + 2
    done()
  })

  b.bench('add#3', () => {
    return new Promise((resolve) => {
      let x = 4 + 2
      resolve()
    })
  })
})
```

**Comment by jdalton** [comment]
I have no opinion.

**Comment by Hypercubed** [comment]
@fanatid I'm working on just that.  Keep watch.

**Comment by Hypercubed** [comment]
@fanatid if you are still interested I made this:  https://github.com/Hypercubed/chuhai
