### ISSUE TITLE
Setup and Teardown per iteration?

### ISSUE THREAD

**Issue by shobhitg** [bestiejs/benchmark.js#132]
I have been browsing through all the opened/closed issues here, but still not sure why isn't there a facility to be able to setup or teardown every iteration for benchmark tests.

I am testing sorting algorithms, and wish to be able to provide a cloned input array in every iteration. Cloning array is simple thing, but yet I don't want it to be part of my code to be benchmarked. It should be in setup, which should run once for every iteration 'in an unclocked manner'.

Is this something planned in future? I am okay if it is not  async version and takes much longer as long as results are accurate.

**Comment by jdalton** [comment]
setup and teardown of each iteration is rough. You can include the array creation in your benchmarks so that they're relative to each other at least.

**Comment by shobhitg** [comment]
Thanks. I guess having same setup for each benchmark test will make them even.
