### ISSUE TITLE
setup() not always called when using defer:true option

### ISSUE THREAD

**Issue by mpotra** [bestiejs/benchmark.js#136]
It appears that when using the `defer` option, the `setup` function is not called before each test anymore. Instead, it is called twice *(in my case always twice)*, each time followed by the test function executed correctly; after that, there's a huge number of calls to the test function, without calling `setup()` before.

Here's my code:
```javascript
suite
.add('something', function (deferred) {
  console.log('test() called');
  fastConsume(() => { console.log('  - test() function finished'); deferred.resolve(); });
}, {
  defer: true,
  setup: function() {
    var fastConsume = (done) => done();
    console.log('setup()');
  }
})
.run({async: true}); // async true/false doesn't make a difference.
```

**Output log:**
```
setup()
test() called
  - test() function finished
setup()
test() called
  - test() function finished
test() called
  - test() function finished
test() called
  - test() function finished
test() called
  - test() function finished
[goes on repeating, until process crashes with ReferenceError below]
```

There are several more `setup()` calls in-between this large number of test function calls.
In my log, out of 13603 lines, `setup()` is called again (after the two correct calls in the beginning - L5,L8)  three more times (L317, L1274, L5233).
Full log here [http://pastebin.com/JRTjm7Tb](http://pastebin.com/JRTjm7Tb)

**Crash log**
```
  fastConsume(() => {
  ^

ReferenceError: fastConsume is not defined
    at suite.add.defer (mytestfile.js:23:3)
    at Deferred.d14635670581491.fn (eval at createCompiled (/somewhere/node_modules/benchmark/benchmark.js:1709:16), <anonymous>:9:25)
    at Deferred.eval (eval at createCompiled (/somewhere/node_modules/benchmark/benchmark.js:1709:16), <anonymous>:26:59)
    at cycle (/somewhere/node_modules/benchmark/benchmark.js:2043:26)
    at /somewhere/node_modules/benchmark/benchmark.js:730:35
    at Timeout._onTimeout (/somewhere/node_modules/benchmark/node_modules/lodash/lodash.js:2412:43)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

*benchmark.js version: 2.1.0*
*Node.JS: versions 6.0.0 and 5.11.0*

**Comment by mpotra** [comment]
Just a quick update: same behavior with `defer: false`.

So, regardless of `defer` setting, `setup()` is not always called before test `fn()` - only a few times in the beginning and occasionally in-between `fn()` calls.

**Comment by jdalton** [comment]
Hi @mpotra!

This is by design. The setup is executed before each test loop where a test is executed so-many times until an accurate measure is able to be performed. In the setup you can access `this.count` which will be the count of the test loop to come.

**Comment by mpotra** [comment]
Thank you very much @jdalton for the explanation.

There's still one bit that bothers me. With `defer` set to `true`, the suite crashes with the `ReferenceError` mentioned in the first post.
Without `defer` it does indeed complete.

Any ideas to what I might be doing wrong, that triggers the error?

**Comment by jdalton** [comment]
When deferred it likely cant compile and inline into a single function so any local vars of setup would not be available to test. You'll have to expose them on the global or an object on the global.

**Comment by mpotra** [comment]
I noticed that only arrow functions get compiled, but sometime while the loop is running even they get GCd for some reason, just as in the log I posted. I guess I'll just go with storing them globally.

Thank you for your help, and apologies for the invalid post.

**Comment by mpotra** [comment]
Apparently the error that I mentioned in my first post, is due to a bug in V8: https://bugs.chromium.org/p/chromium/issues/detail?id=604033
