### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by zoltan-mihalyi** [bestiejs/benchmark.js#139]
I apolosige if it is a dumb question, but i couldn't find the release notes.
Could you tell me where they are, or what the major changes are among 1.0, 2.0 and 2.1?

**Comment by jdalton** [comment]
Hi @zoltan-mihalyi!

There aren't any release notes. The major change between v1 and v2 was dropping older environment support (old java environments, older browser environments like IE8) and adopting a dependency on Lodash.

For the 2.0 -> 2.1 changes you can see the [tag compare](https://github.com/bestiejs/benchmark.js/compare/2.0.0...2.1.0).

**Comment by zoltan-mihalyi** [comment]
Thank you for the response!
