### ISSUE TITLE
Website does not appear to be working

### ISSUE THREAD

**Issue by neocotic** [bestiejs/benchmark.js#141]
Every URL on the website triggers a download of a file. Is this intentional? Looks suspicious to me.

**Comment by jdalton** [comment]
The website https://benchmarkjs.com/ doesn't trigger downloads for me.

**Comment by neocotic** [comment]
Hmm, strange. I just checked and it's also not doing it for me on my mobile. Must be something very strange with my corporate network as I'm currently on my work laptop. Very strange.

Thanks for checking anyway.

**Comment by jdalton** [comment]
No problem :)
