### ISSUE TITLE
Benchmark borks if there are no script tags on the page. 

### ISSUE THREAD

**Issue by Morklympious** [bestiejs/benchmark.js#142]
You can consider this a wild edge case (and feel free to close as wont-fix), but I'm working on building a performance app for funsies, and I'm using a Vdom library in conjunction with benchmarkjs.

For the longest time I was mounting my app straight onto `document.body` (wherein I load my single script tag bundle), meaning the `script` element gets wiped on mounting, but stays in memory so it's able to be executed, but then the offending function is the [attempt to inject a script tag next to the first found script tag](https://github.com/bestiejs/benchmark.js/blob/master/benchmark.js#L660)

This, again, is an __extremely__ unlikely use case, that being that for some reason you'd want to axe all of the script tags on a page, but I just wanted to have this documented somewhere in case someone runs into a similar problem and has a google-fit trying to search for a solution. 

I might try my hands at a PR when I get some time. :)

**Comment by jdalton** [comment]
I'd be up for a PR :)

**Comment by jdalton** [comment]
Moved to #144.
