### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by treshugart** [bestiejs/benchmark.js#145]
I'm getting `Uncaught ReferenceError: define is not defined` whenever I try and run a test. For example, this fails:

```js
import Benchmark from 'benchmark';
const test = new Benchmark(function () {
  // do something;
});
test.run();
```

I'm using Webpack to bundle things. Possibly related, Webpack is also trying to load the readme, license and package.json files.

**Comment by jdalton** [comment]
Hi @treshugart!

I know there's some browserify issues but attempting to load readme, license, and other files seems pretty far off. If you dig, keep investigating and report back.
