### ISSUE TITLE
How to make it go faster?

### ISSUE THREAD

**Issue by githubaccount624** [bestiejs/benchmark.js#163]
I'm writing a library that needs to be very efficient.

I am often making changes where I need do a benchmark every change.

Benchmark js takes around 85 samples for each item in the suite and ends up taking 30 seconds total.

Even though it would be less accurate, I'm looking for a way of making it much quicker during development. Ideally between 1 and 5 seconds.

I looked through the options and couldn't find one to make it complete faster, even though I tried all the ones that looked promising. Regardless, it takes around 85 samples.

Is there any way to do this?

**Comment by jdalton** [comment]
Hi @githubaccount624!

Try adjusting some of the [Benchmark.options](https://benchmarkjs.com/docs#options) like `minSamples`, `minTime`, and `maxTime`.

**Comment by githubaccount624** [comment]
Yeah I tried all of those

**Comment by jdalton** [comment]
Setting them do make a difference.  I donno what else to tell you.

**Comment by githubaccount624** [comment]
`minSamples`: The default is 5. Around 85 are generally being run. This doesn't apply. Maybe if it was `maxSamples`.

`minTime`: Again, I'm looking for a maximum amount of time taken. Setting a minimum doesn't do anything.

`maxTime`: Seems like the only option available that would apply in this situation but setting it doesn't seem to do anything. The default value is 5. Even if I set it to 1, the benchmark takes the same amount of time. I'm not sure if it's bugged or doesn't work how I think it does but it doesn't seem to help in this situation either.

**Comment by jdalton** [comment]
The combo of `minSamples` and `maxTime` are factors for when a benchmark has maxed out. You can set time units to fractions of a second too, like `0.5`.

**Comment by githubaccount624** [comment]
I must be missing something. I tried `.run({ 'async': false, 'maxTime': .1, 'minSamples': 0 });`, but it's still the same. Takes 30 seconds total and runs 85 samples for each test.

Could you give me an example of an options setup that would significantly shorten the benchmark time?

**Comment by jdalton** [comment]
Try setting the `minTime` to a low non-zero number, like '0.01'.

**Comment by githubaccount624** [comment]
Doesn't seem to be doing anything. It seems like the ability to rapidly run benchmarks does not exist.

**Comment by jdalton** [comment]
These settings do control the benchmark timing.
It sounds like what you're wanting is more suited to using `console.time` and a for-loop.

**Comment by githubaccount624** [comment]
`console.time` and a for loop doesn't let you very easily test for variance nor use statistical theorems that I don't understand to get a better result.

If instead the benchmark were run for 10 samples, it would run 10x faster for me and still be decent enough for development testing. It does not seem that there is a way to do this.

I'm not sure why this is closed. If benchmark.js does not have this feature shouldn't the label be changed to feature request or something?
