### ISSUE TITLE
jsperf is not match what i get by using benchmark.js

### ISSUE THREAD

**Issue by magicly** [bestiejs/benchmark.js#177]
hi, I see https://jsperf.com/math-perf-alsotang. its result is so big that i dont believe. my computer is mac pro 2.5 GHz Intel Core i7,  Google Chrome	54.0.2840.98 (正式版本) （64 位）.  

https://jsperf.com/math-perf-alsotang result tell me 
```
Math.log(1000000) / 256 * 1024 / Math.pow(43, 2)
```
this operation can be runned 1 billion times one second, which means that operation just cost 2.5 cpu cycles?

I write test code using benchmark.js on node(version 7.1.0, v8: '5.4.500.36') and also on my chrome, but get a much smaller result. 100 million operation per second, which mean 1/10 of what jsperf give me.

```
const Benchmark = require('benchmark');

var suite = new Benchmark.Suite;

// add tests
suite.add('RegExp#test', function() {
  Math.log(1000000) / 256 * 1024 / Math.pow(43, 2)
})
.add('String#indexOf', function() {
  Math.log(1000000000) / 256 * 1024 / Math.pow(433, 2)
})
// add listeners
.on('cycle', function(event) {
  console.log(String(event.target));
})
.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').map('name'));
})
// run async
.run({ 'async': true });

```

Is there sth I missed? thanks~

**Comment by jdalton** [comment]
Hi @magicly!

Node and a browser can show different performance characteristics. In my own Chrome 54 I'm seeing results closer to your Node score. In the end though they're ops per seconds are so high it won't likely matter.
