### ISSUE TITLE
Exception thrown from internals of Benchmark on simple example...

### ISSUE THREAD

**Issue by getify** [bestiejs/benchmark.js#180]
I tried this simple example (node v7):

```js
var Benchmark = require("benchmark");

Benchmark.options.onStart = function onStart(evt){
	console.log("onStart",evt.target.name);
};

var main = Benchmark.Suite("main");

main.add("test",function(){
	var x = new Array(1400);
});

main.run();
```

When I run this on the command line, the output I get is:

![bug](https://cloud.githubusercontent.com/assets/150330/21107278/ca4199b0-c056-11e6-9e2c-61166dfce7fc.png)

1. I'm not sure why `onStart` is getting called twice?
2. I don't understand why my usage is causing this exception?

Am I missing something?

**Comment by jdalton** [comment]
Which version of Benchmark.js are you using?

**Comment by getify** [comment]
2.1.2

**Comment by jdalton** [comment]
Narrowed the bug down to https://github.com/bestiejs/benchmark.js/commit/bb1511c1a53147d80da478b75728a18f4950f59f. I have a patch. Going to test it a bit though.

**Comment by getify** [comment]
thanks for the update! glad i'm not crazy. :)

**Comment by getify** [comment]
Anything I can do to help here?

**Comment by jdalton** [comment]
Naw. Not really happy with the fix so will be kicking it around a bit. It's getting to be that holiday time where I either have zero or tons of down time :grinning:

**Comment by getify** [comment]
Can I safely apply this patch temporarily on my local install and move forward, or is it likely that the eventual fix will change behavior and I should just wait?

**Comment by jdalton** [comment]
This patch is fine to apply. The second attempt will just refine and clarify some things.
