### ISSUE TITLE
Some duplication and mismatch in the benchmarkjs.com/docs

### ISSUE THREAD

**Issue by vsemozhetbyt** [bestiejs/benchmark.js#181]
`Benchmark.prototype.emit`, `Benchmark.prototype.listeners`, `Benchmark.prototype.off`, and `Benchmark.prototype.on` are mentioned twice (after `Benchmark.prototype.compare(other)` and `Benchmark.Suite.prototype.clone(options)`) under the names `Benchmark.Suite.prototype.emit`, `Benchmark.Suite.prototype.listeners`, `Benchmark.Suite.prototype.off`, and `Benchmark.Suite.prototype.on`. Their link anchor ids are also used twice as `...#prototype_...`. They are also mentioned twice  in the TOC by two different set of names.

**Comment by jdalton** [comment]
Yep, they are technically different API points that need documenting.
