### ISSUE TITLE
Question: untimed setup portion

### ISSUE THREAD

**Issue by Poincare** [bestiejs/benchmark.js#183]
I have a quick question regarding `benchmark.js.`I'm currently building some benchmarks that require some set up before the benchmark itself can be executed and I would like this set up to be placed outside of the timed portion of the code. Is there a utility or option that `benchmark.js` provides to do this?

I tired `onCycle`,`setup` and `onStart` but none of these seem to execute just before the benchmark itself *every time*, which is the behavior that I need.

**Comment by jdalton** [comment]
Hi @Poincare!

The `setup` is outside of the timed portion. It is executed in close proximity though so heavy setups can in extreme cases impact measurements.

**Comment by Poincare** [comment]
But, is the `setup` called before every call of the benchmark? I need to clear and reset state every time that the benchmark is called and it seems that `setup` isn't called every time the benchmark is run?

**Comment by jdalton** [comment]
A benchmark is sampled several times per run. The sample run looks like:
```txt
<setup>
<start timer>
<bench loop>
<stop timer>
<teardown>
```

**Comment by Poincare** [comment]
Ah. So I guess there's no way for me to do the following:

```
<loop over samples>
  <setup>
  <start timer> 
  <single iteration of bench>
  <end timer>
<end loop over samples>
```

**Comment by jdalton** [comment]
> Ah. So I guess there's no way for me to do the following?

No. But the `setup` does have `this.count` which will be the number of iterations of the bench loop per that sample. So you can use it to build up DOM elements or other scaffolding.

**Comment by Poincare** [comment]
That makes sense - thank you.

Out of curiosity, is there a reason why the system is structured in this way? Would having a small function that runs before the bench iteration impact measurements? I guess that certainly makes sense if not all of your benchmarks had that kind of function, but if such a function were present across all of the benchmarks, do you think it would affect the timing/CPU cycle deltas between the benchmarks?

**Comment by jdalton** [comment]
For more info check out this [post from 2010](https://calendar.perfplanet.com/2010/bulletproof-javascript-benchmarks/).
