### ISSUE TITLE
Question: Approaches to factoring the impact of GC?

### ISSUE THREAD

**Issue by kirbysayshi** [bestiejs/benchmark.js#185]
Is it possible to factor in the variance (+-%) of a benchmark when determining the winner (mathematically speaking)? I'm looking for an approximation to compare garbage collection effects with benchmarks, and I assume that the largest factor in that variance is GC.

Or perhaps there is another way of measuring which benchmark would create less garbage and thus be more applicable to a 60fps environment (like a game, for example)?

I assume that the fastest benchmark is not always the smoothest (for example using an object pool), but am having trouble proving that assumption via benchmarks.

I can go into more detail if necessary!

**Comment by jdalton** [comment]
Hi @kirbysayshi!

It's been a while! I believe there is some logic in place to factor in margin of error. That said a high margin of error (MoE) is an indicator of instability (usually caused by GC). We do store the stats so you could access them and report the benchmark with the highest or lowest MoE.

**Comment by kirbysayshi** [comment]
Thanks for the reply! Also... hiiiiiii!

Is there anything else that can cause instability besides GC?

And what about the benchmarks themselves... are there any recommended patterns for writing tests that would guarantee GC will be recorded during the clocked loop? Right now I'm guessing that for some of my tests the GC might not trigger until after the clocked test loop due to whatever heuristics are in place in individual browsers.

**Comment by jdalton** [comment]
It could be that you're doing something conditionally (like you think a value is one thing but it's actually accumulating). As for recommendations I'd say avoid creating your own test loop. The benchmarks themselves are repeated so there's no need for `for (var i=0; i < 1000; i++) myTest()` in your benchmark.
