### ISSUE TITLE
Any way of passing arguments to fns?

### ISSUE THREAD

**Issue by bali182** [bestiejs/benchmark.js#189]
**NOT A BUG**

What I'm trying to do is create one expensive but immutable object and pass it around for all benchmarks in a suite. Pseudocode below:

```js
const suite = new Benchmark.Suite({
  // This is not a valid config option, I'm looking for something that is.
  createArguments() {
    // Create expensive object which won't be mutated by benchmarks 
    return new Array(1000000).fill(1).map(Math.random)
  }
})
```

And in the benchmarks I'd like to have access to this as an argument, or any other way without polluting the outer scope with variables:

```js
suite.add('remove by index using filter', largeArray => {
  largeArray.filter((_, i) => i !== 50000)
})

suite.add('remove by index using slice and concat', largeArray => {
  largeArray.slice(0, 50000).concat(largeArray.slice(50001))
})

suite.add('remove by index slice and spread', largeArray => {
  [...largeArray.slice(0, 50000), ...largeArray.slice(50001)]
})

// and so on...
```

Is this possible somehow?

**Comment by jdalton** [comment]
Hi @bali182!

The `setup` can be used to initialize values, but depending on your environment they may not be local variables. In that case you'd want to bolt them to a global.

**Comment by bali182** [comment]
@jdalton  Thank you!
