### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by rgranger** [bestiejs/benchmark.js#192]
Webpack emits the following warning when we import benchmark.js

```javascript
import Benchmark from 'benchmark'
```

```
WARNING in ./~/benchmark/benchmark.js
Critical dependency: the request of a dependency is an expression
```

Moreover, when i'm running the test suite given in this example, i get plenty of those errors even though the test completes with success. : 

```
Uncaught ReferenceError: define is not defined
```
So i can't simply import this module in my project to compare the performances of two functions. Do I have to create a separate application and to define lodash in global scope, in order to compare 2 functions which are in my project ?

This would be annoying...

**Comment by jamesc892** [comment]
Bump

**Comment by samvv** [comment]
I can confirm this is a real issue. I was about to test my library which depends heavily on CommonJS and this issue made it virtually impossible to benchmark it.

**Comment by jdalton** [comment]
You don't have to include `Benchmark` in your bundle. Webpack is super configurable.

**Comment by rgranger** [comment]
Yes, i know i can put Benchmark as a global variable. But that is how I want to use it.

**Comment by drewlustro** [comment]
+1 this is busted.

**Comment by jdalton** [comment]
I'm closing this because I won't be patching it. If someone wants to send a PR then I'll totally apply it.

**Comment by drewlustro** [comment]
No worries @jdalton ! There's a solid solution in #128 - perhaps we can add it to the documentation?
