### ISSUE TITLE
Error when running in browser

### ISSUE THREAD

**Issue by andyhall** [bestiejs/benchmark.js#208]
Hi,

Running a minimal benchmark suite (the "sample usage" code from the readme), I get an error when the code has been compiled with webpack and run in current Chrome (v67). 

The error triggers from [this line](https://github.com/bestiejs/benchmark.js/blob/master/benchmark.js#L681), the specific error is that `define` is undefined (heh). 

I was able to work around the issue by doing the following before running the suite:

```js
	window.define = {}
	window.define.amd = {}
```

Thanks!

**Comment by jdalton** [comment]
Hi @andyhall!

Webpack is likely trying to shim AMD in some way. Ensure you disable it in your webpack bundle options.

**Comment by andyhall** [comment]
Hey @jdalton,

Unless I'm missing something, the error throws because `define` **isn't** shimmed in, but benchmark still evaluates it. Shimming it in avoids the error. 

Note that I'm not using AMD or anything, just webpack default behavior - no configuration except paths.

(To be precise, the code that tries to evaluate `define` in global scope seems to be a dynamically created function that's getting run through `eval` or similar. It looks like some AMD specific code is getting run even though AMD isn't present.)

**Comment by jdalton** [comment]
Benchmark doesn't assume an AMD loader exists. By default Webpack is tripping the AMD detection. You have to explicitly disable AMD in webpack bundles.
