### ISSUE TITLE
Locale support to format numbers

### ISSUE THREAD

**Issue by pimlie** [bestiejs/benchmark.js#210]
Would you consider accepting a PR to include locale support through an optional dependency like [Numeral.js](https://github.com/adamwdraper/Numeral-js)?

The first time I ran a benchmark I thought it was really cool (but strange and doubtful) you measured `ops/sec` with 3 digit precision. Took a while before I noticed the locale issue...

**Comment by jdalton** [comment]
Hi @pimlie!

Can you explain the locale issue in more detail? What did you see to what did you expect.

**Comment by jdalton** [comment]
Ah nice! Are you familiar with the [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) APIs?

**Comment by pimlie** [comment]
I have looked at Node's [Internationalization](https://nodejs.org/api/intl.html) support but `Number.toLocaleString` seems not to be locale-aware without re-compiling Node which seems a bit excessive  for 'just' changing the number separators.

**Comment by jdalton** [comment]
I'm up for a PR that enhances Intl when possible, so an optional install and a code path for `toLocaleString` would be great!

**Comment by jdalton** [comment]
Moved to #216 💪
