### ISSUE TITLE
great margin of error with `functions` assigned to `this` object

### ISSUE THREAD

**Issue by Feirell** [bestiejs/benchmark.js#211]
This does not directly belong to benchmarkjs but I was wondering if you are able to explain an interesting behavior:

```js
const {
    Suite
} = require('benchmark');

const suite = new Suite();

class ExampleClass {
    constructor(v) {
        this.func = v ? function () {} : () => {};
    }
}

// function ExampleClass(v) {
//     this.func = v ? function () {} : () => {};
// }

// class ExampleClassA {
//     constructor() {
//         this.func = function () {};
//     }
// }

// class ExampleClassB {
//     constructor() {
//         this.func = () => {};
//     }
// }

suite.add('function', () => {
    new ExampleClass(true);
    // new ExampleClassA();
});

suite.add('arrow function', () => {
    new ExampleClass(false);
    // new ExampleClassB();
});

suite.on('complete', () => {
    console.log("Suite completed:\n  %s", suite.map(b => b.toString()).join("\n  "));
});


suite.run();
```

This suite results in the following output for me:
```text
Suite completed:
  function x 363,047,240 ops/sec ±16.73% (88 runs sampled)
  arrow function x 396,434,089 ops/sec ±0.74% (88 runs sampled)
```

As you can see the first benchmark has a great margin of error, are you able to reason this?
You can exchange the es6 class with the function style constructor it won't matter.
But the margin of error is almost completely gone when you exchange the combined class with the two separate classes.

My understanding is that the assigning of the `function` to the `this` property rewrites the `this` for the `function` which takes time but this does not answer the great margin of error.

Thank you very much for your time and help.

node version `v8.12.0`
`yarn.lock`
```text
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


benchmark@^2.1.4:
  version "2.1.4"
  resolved "https://registry.yarnpkg.com/benchmark/-/benchmark-2.1.4.tgz#09f3de31c916425d498cc2ee565a0ebf3c2a5629"
  integrity sha1-CfPeMckWQl1JjMLuVloOvzwqVik=
  dependencies:
    lodash "^4.17.4"
    platform "^1.3.3"

lodash@^4.17.4:
  version "4.17.11"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.11.tgz#b39ea6229ef607ecd89e2c8df12536891cac9b8d"
  integrity sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==

platform@^1.3.3:
  version "1.3.5"
  resolved "https://registry.yarnpkg.com/platform/-/platform-1.3.5.tgz#fb6958c696e07e2918d2eeda0f0bc9448d733444"
  integrity sha512-TuvHS8AOIZNAlE77WUDiR4rySV/VMptyMfcfeoMgs4P8apaZM3JrnbzBiixKUv+XR6i+BXrQh8WAnjaSPFO65Q==
```

**Comment by jdalton** [comment]
Hi @Feirell!

Engines will optimize the call site and the branch. I'm guessing the branch takes a bit more profiling before it can be eliminated. Based on the results though it doesn't look like it matters. I use arrow functions for everything until I explicitly need a regular one. They're fine now.

**Comment by Feirell** [comment]
> I'm guessing the branch takes a bit more profiling before it can be eliminated.

So it will be slower at first but after anough profiling it will speed up, and this causes the the high margin of error?
