### ISSUE TITLE
Using arrow function will throw an error

### ISSUE THREAD

**Issue by SylvanasGone** [bestiejs/benchmark.js#225]
I checked the issues list and believe it isn't a duplicate.
```js
// everything is ok
.on('complete', function() {
    console.log('Fastest is: ' + this.filter('fastest').map('name'))
  })

// "TypeError: this.filter is not a function"
.on('complete', () => {
    console.log('Fastest is: ' + this.filter('fastest').map('name'))
  })
```
As the code shown above, it seems there is a conflict between arrow function and 'this.filter'.
I'm not sure it is a bug or just my wrong usage, hope someone would help me, thank you!

**Comment by joakim** [comment]
I think it's wrong usage, benchmark.js expects a normal function :) A normal function would get the `this` of the suite, but `this` in an arrow function is always that of the lexical scope.

But accessing `suite` directly seemed to work fine for me:
```js
suite.add('RegExp#test', () => {
  /o/.test('Hello World!');
})
// ...
.on('complete', () => {
  console.log('Fastest is ' + suite.filter('fastest').map('name'));
})
```

**Comment by SylvanasGone** [comment]
@joakim You are right, I did miss the basic feature of arrow function, thanks!

**Comment by Uzlopak** [comment]
Actually the solution could be to pass the instance as first parameter by benchmark.js
