### ISSUE TITLE
Project Active?

### ISSUE THREAD

**Issue by fishcharlie** [bestiejs/benchmark.js#232]
Is this project even active anymore? No commits since 2018. No releases since 2017. 11 open pull requests (one of them being a security patch, #231) and 23 open issues.

If not, please take the 30 seconds required to archive this repository on GitHub to indicate to users that it's not longer being maintained...

**Comment by celesteking** [comment]
They haven't even managed to actually write sane documentation for this package. This project is definitely dead, but what are the alternatives?

**Comment by polarstoat** [comment]
@celesteking I've used [benny](https://www.npmjs.com/package/benny) before (which itself uses benchmark.js under the hood) and found the documentation for that simpler

**Comment by celesteking** [comment]
You da man! That's exactly the package I've picked as an alternative to bechmark.js, despite it being just a wrapper around it. You've just confirmed I made the right decision. ;)

**Comment by jdalton** [comment]
Not really happy with the tone here.
