### ISSUE TITLE
Add asynchronous support to setup and teardown.

### ISSUE THREAD

**Issue by octatone** [bestiejs/benchmark.js#70]
Hello,

I was trying benchmark performance between indexedDB#add and indexedDB#put with the same data sets, but according to [this closed issue](https://github.com/bestiejs/benchmark.js/issues/53) it is not possible to properly setup with asynchronous function calls in benchmark.js.

IndexedDB is asynchronous only.  Opening, creating, CRUD, etc. are all done async in the browser.

Ideally my benchmark would look something like this pseudocode:

``` pseudocode
setup = function () {
  // open database connection/create db
  // create store
  // populate benchmark data
}

teardown = function () {
  // delete database
  // close db connection
}

test1 = function add () {
  // get transaction request
  // while (data) request.add
}

test1 = function put () {
  // get transaction request
  // while (data) request.put
}
```

I propose adding support for asynchronous for setup and teardown as more and more modern browser apis are async only.

**Comment by chesleybrown** [comment]
Guess you never got very far over the weekend...? :cry:

**Comment by superkhau** [comment]
:+1:

**Comment by vjpr** [comment]
+1

**Comment by elyas-bhy** [comment]
+1

**Comment by jdalton** [comment]
Moved to #174.
