### ISSUE TITLE
Passing variables to the setUp method

### ISSUE THREAD

**Issue by pkozlowski-opensource** [bestiejs/benchmark.js#73]
Firstly, thnx for all the effort you've guys put into benchmark.js - much appreciated. 

I'm opening this issue more like a request for comments / question rather than a very precise bug report. My use case is the following one: I'm using benchmark.js with the code that is written using the CommonJS and the code under test needs to be `require`-ed in the `setUp` method. But since benchmark.js is "compiling" / "stringifing" benchmark methods I can use the closure scope to get my hand on the `require` method (or maybe I simply don't know how to do it properly...).

What I'm doing as of today is a work-arround that consists of passing a non-standard option to the benchmark like so:

``` javascript
{
    setup: setUp,
    teardown: function () {
        document.body.removeChild(outDiv);
    },
    require: require
}
```

and then, in the `setUp` method I'm doing: `var require = this.benchmark._original.options.require;`. This way I can access the `require` variable in both the setup and test method.

While the above works I'm kind of not happy with it and suspect that other people might have a similar use-case of passing a variable defined in the closure scope to benchmark methods. Given the above my questions are the following one:
- is there a better / canonical method of tackling this use-case?
- if not, do you think there is something we could do on the benchmark.js side to support this and similar use-cases?

Would be grateful for any input.

**Comment by internalfx** [comment]
@zenoamaro Thanks for that.
