### ISSUE TITLE
.resolve() method on deferred object not documented

### ISSUE THREAD

**Issue by tmcw** [bestiejs/benchmark.js#76]
The examples show using `deferred.resolve()` when a function has `defer: true` set, but there's no documentation for this method or for any other methods on the object passed to an async benchmark.

**Comment by springmeyer** [comment]
Would also love to see docs on this. I think I figured it out (https://gist.github.com/springmeyer/a67d8d77057d30fc4bbe) but only by finding https://github.com/bestiejs/benchmark.js/blob/ad06611943dd2741474ecfcce446df23f23347af/test/test.js#L898-L909

**Comment by tmcw** [comment]
looks like this is documented on a code level https://github.com/bestiejs/benchmark.js/blob/19a894897bad3ab51102ce5ee558efbca598645d/benchmark.js#L707
