### ISSUE TITLE
Question about the 2.0.0-pre

### ISSUE THREAD

**Issue by thomas-lee** [bestiejs/benchmark.js#83]
I have tried to use the benchmark 2.0.0-pre following the sample. It gives me the following error

Uncaught TypeError: object is not a function  line:1890
It seems all the bench are reset and original loaded lodash functions are removed.  on line 2147

benchmark 2.0.0-pre with lo-dash 2.4.1

    require([
        "benchmark"
    ], function (
        Benchmark
    ) {
        var suite = new Benchmark.Suite;

        // add tests
        suite.add('RegExp#test', function () {
                /o/.test('Hello World!');
            })
            .add('String#indexOf', function () {
                'Hello World!'.indexOf('o') > -1;
            })
            // add listeners
            .on('cycle', function (event) {
                console.log(String(event.target));
            })
            .on('complete', function () {
                console.log('Fastest is ' + this.filter('fastest').pluck('name'));
            })
            // run async
            .run({
                'async': true
            });
    });

And then i have tried to run the unitTest and example. It doesn't work either.
unitTest gives similar error as above. But the jsperf example (benchmark2.0.0-pre+lodash3.0.0-pre)
gives me the following error log.

message: Uncaught TypeError: Cannot read property 'toFixed' of undefined
fileName: http://192.168.200.174/benchmark/benchmark.js
lineNumber: 1555

My questions are what the difference between 1.0.0 and 2.0.0pre?
Is it just separate the utility function from benchmark to lodash and platform.js?
And then which version of lodash should i use for 2.0.0pre benchmark?

Thanks  a lot.

**Comment by awstlaur** [comment]
I got the same error on the same line at one point!

I'm using this in a nodejs context, so I wanted to just run their node tests in the test folder in this repository. I ended up needing lodash3.0.0-pre, which is available to download from its github. I also had to change the path name on the call which loads qunit, but that's a different story. The tests ended up passing, so I'm currently trying to figure out if there are any lingering references to lodash2.4.1 floating around in my own setup.

**Comment by awstlaur** [comment]
I got this suite example to work! The short answer is I am using lodash3.0.0-pre, platform1.3.0, and requirejs2.1.15. I will post more details in a subsequent comment; I just wanted to get this info down quickly because I see one of the developers labeled this issue 8 minutes ago.
