### ISSUE TITLE
Tests no run when passing options to `Suite.prototype.add`

### ISSUE THREAD

**Issue by paldepind** [bestiejs/benchmark.js#85]
I'm trying to test the performance of a library and stumbled upon something I don't quite understand. I've reduced it to the following: 

```javascript
suite.add('Test 1', {
  setup: function() {
    // Do setup
    var s = stream(); // <- Offending line
  },
  fn: function() {
    true;
  },
})
.add('Test 1', function() {
  var s = stream();
  true;
})
// add listeners
.on('cycle', function(event) {
  console.log(String(event.target));
})
.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').pluck('name'));
})
// run async
.run({ 'async': true });
```

If I run the above script with node I get the following output:
```
Test 1: 
Test 2 x 280,378 ops/sec ±1.33% (98 runs sampled)
Fastest is Test 1
```

The first line prints immediately indicating that no benchmarks are actually run for the first test.

If I instead run the code with the line marked offending commented out I get expected output:

```
Test 1 x 400,909,017 ops/sec ±2.46% (67 runs sampled)
Test 2 x 110,054 ops/sec ±2.21% (81 runs sampled)
Fastest is Test 1
```

`stream` is a function and as you can see calling it in the second test is not an issue. But for reasons I don't understand its presence prevents the first test from running.

**Comment by jdalton** [comment]
In the repo master branch we've modified the way of handling benchmarks in node to avoid compilation complications with local variables, until the bump you can work around this issue by assigning `stream` to `global.stream = stream`.

**Comment by paldepind** [comment]
Thank you for your quick reply. That fixes my issue.

I'll get back to writing benchmarks!

**Comment by adrian-moisa** [comment]
I was strugging with a similar issue in the browser (not node.js). I was trying to use a localy scoped variable inside a benchmark suite. However I kept getting this error: 

    ReferenceError: Collection is not defined at Benchmark.define.amd.uid1450...

The solution was to define a global variable (omitting `var` keyword in front of the variable declaration). Here's a sample script for anyone learning to use benchmark.js. I think this should be explicitelly stated in the documentation. If it is, should be made more visible.

	define([
		'benchmark',
		'engine/utils/collection'
	], function (
		Benchmark,
		Collection
	) {
		global = {}; // <!> Take note: no var keyword <!>
		global.Collection = Collection;

		var suite = new Benchmark.Suite('collection'),
			body = document.getElementById('body');

		suite.add('new Collection()', function () {
			   var collection = new Collection();
			})
			.add('collection.add()', {
				fn: function () {
					collection.add(global.index + global.count, global.count++);
				},
				setup: function () {
					var collection = new global.Collection();
					global.count = 0;
					global.index = 'abc';
				}
			})
			.on('cycle', function (event) {
				console.log(String(event.target));
				body.innerHTML += String(event.target) + '</br>';
			})
			.on('complete', function () {
				console.log('Fastest iss ' + this.filter('fastest').pluck('name'));
				body.innerHTML += 'Fastest is <b>' + this.filter('fastest').pluck('name') + '</b></br></br>';
			})
			.on('error', function (event) {
				console.log(event);
			})
			.run({'async': true});
	});
