### ISSUE TITLE
Documentation for stats

### ISSUE THREAD

**Issue by hdgarrood** [bestiejs/benchmark.js#89]
I'm trying to make sense of the `stats` that result from a benchmark and the [docs](http://benchmarkjs.com/docs#prototype_stats) could be better. For example:

* Am I correct in thinking that the units of `stats.mean` are seconds? And that this value represents the mean time taken for the given function to complete?
* Does the length of `stats.samples` vary because Benchmark does the minimum amount of tests necessary to reach some threshold margin of error? If so, what is it?

I'd be happy to help update the docs regarding these questions, by the way.

**Comment by hdgarrood** [comment]
I looked at the source and figured out the answers:

* Yes, and yes (although it is the sample mean, which is an estimate of the population mean). From https://github.com/bestiejs/benchmark.js/blob/master/benchmark.js#L2541-L2546
* No, the length of `stats.samples` varies because a benchmark finishes after the minimum sample size has been reached, and after the elapsed time exceeds the maximum amount of time allowed per benchmark. From https://github.com/bestiejs/benchmark.js/blob/master/benchmark.js#L1983-L1984

**Comment by hdgarrood** [comment]
Also, another thing that I think would be useful to indicate in the docs is the confidence level that the margin of error is based on. Something like:

> Margin of error: the margin of error of the sample mean, at the 95% level. A 95% confidence interval may be constructed by: (mean - moe, mean + moe)

(I think the above is correct.)

Finally, if I want to create graphs of my benchmarks, should I be using the above confidence intervals for the error bars?

**Comment by jdalton** [comment]
> I'm trying to make sense of the stats that result from a benchmark and the docs could be better.

PRs would be welcomed for doc improvements.

> Finally, if I want to create graphs of my benchmarks, should I be using the above confidence intervals for the error bars?

I think [stats.stackexchange](http://stats.stackexchange.com/) could help answer that.
