### ISSUE TITLE
benchmark only running a single iteration

### ISSUE THREAD

**Issue by mbroadst** [bestiejs/benchmark.js#90]
I've got two (rather contrived) examples of benchmarks here for a benchmark in node.js. The first exits out immediately having run a single iteration, while the second prints out hundreds of lines. I'm sure I'm missing something fundamental here, but can't quite figure it out. Any thoughts?

```
var Benchmark = require('benchmark');
 
// this outputs nothing
new Benchmark.Suite()
  .add("TestBuffer", {
    'setup': function() {
      this.buffer = new Buffer();
    },
    'fn': function() {
      console.log(this.buffer);
    }
  })
  .run();
 
// this outputs tons of integers
new Benchmark.Suite()
  .add("TestInt", {
    'setup': function() {
      this.value = 10;
    },
    'fn': function() {
      console.log(this.value);
    }
  })
  .run();
```

**Comment by balupton** [comment]
Looking at the docs you may need to add the suites to an array, and then fire them via Benchmark.invoke, but it produces the same result and doesn't work.

**Comment by schnittstabil** [comment]
Your setup function throws a `TypeError`, check:
```js
$ node
> new Buffer(4)
<Buffer 78 18 01 0b>
> new Buffer()
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

**Comment by d10** [comment]
Yeah, @schnittstabil is right. You can use `Benchmark#on('error', callback)` or `Suite#on('error', callback)` to catch errors with a callback function or specify the [`onError`](https://benchmarkjs.com/docs#options_onError) option when passing options into `Benchmark` or `Suite`.
