### ISSUE TITLE
deferred.resolve() can bottle-neck on nested setTimeout() 4ms clamp when used synchronously

### ISSUE THREAD

**Issue by wanderview** [bestiejs/benchmark.js#92]
While trying to benchmark something for the proposed streams API spec, I ran into an interesting footgun in benchmark.js.

If use `deferred:true` and then call `defered.resolve()` synchronously, then you will end up nesting `setTimeout()` calls with each execution of the test.  This is bad because `setTimeout()` does this per the [spec][]:

> Timers can be nested; after five such nested timers, however, the interval is forced to be at least four milliseconds.

In this particular test it made the results always come out to ~210 ops/sec.  This is basically the 4ms interval translating to a 250 ops/sec limit with some overhead added in.

You might want throw or warn if you detect `deferred.resolve()` being used synchronously.  Alternatively, if you use a native Promise, then the microtask scheduling does not do clamping to 4ms.

When I changed our test to do `Promise.resolve().then(function() { deferred.resolve() })` the ~210 ops/sec jumped up to ~16000 ops/sec.

[spec]: https://developers.whatwg.org/timers.html#timers

**Comment by jdalton** [comment]
I believe this has been resolved in the master branch. If you try `resolve` synchronously now it will hit the call stack limit and error out. Give it a try.
