### ISSUE TITLE
nodejs: is it possible to use 'require' inside the benchmarks?

### ISSUE THREAD

**Issue by angelsanz** [bestiejs/benchmark.js#94]
I've been trying for a while to use node's usual `require` inside both my test `fn` and my `setup` or `teardown` handlers, to no avail. I suspect it isn't working (`ReferenceError: require is not defined`) because the body of those functions is, in the end, being `eval`ed by benchmark.js before it runs, therefore closures are lost.

So that's my question: is there a way to use `require` inside the benchmarks? I'm looking to something as simple as this:

```js
var Benchmark = require('benchmark');
var suite = new Benchmark.Suite();

var _clearRequireCache = function() {
    Object.keys(require.cache).forEach(function(requiredModule) {
        delete require.cache[requiredModule];
    });
};

suite.add('first', function() {
    require(/*path to some local module*/);
}, { teardown: _clearRequireCache})
.add('secondn', function() {
    require(/*path to some other local module*/);
}, { teardown: _clearRequireCache})
.on('cycle', function(event) {
    console.log(String(event.target));
})
.on('complete', function() {
    console.log('Fastest is ' + this.filter('fastest').pluck('name'));
})
.run();
```

**Comment by angelsanz** [comment]
Ah, well. You might of course add
```js
global.require = require;
```
at the beginning of the module where the benchmark is implemented. So, basically all dependencies of a benchmark might as well be dropped in the global scope.

This is still far from optimal... but at least the benchmarks do run.

**Comment by jdalton** [comment]
This is resolved on master. The issue is with the module scope of functions created by `Function(...)`.

**Comment by myndzi** [comment]
I tried the version in master because I was encountering problems trying to benchmark some Node code, and Benchmark.Suite doesn't appear to be exported anymore?

Also seconding the comments elsewhere that the asynchronous API is very much not explained well in the documentation.

**Comment by jdalton** [comment]
> I tried the version in master because I was encountering problems trying to benchmark some Node code, and `Benchmark.Suite` doesn't appear to be exported anymore?

It's exported.

**Comment by myndzi** [comment]
myndzi@test:~$ npm install git+https://github.com/bestiejs/benchmark.js
    benchmark@2.0.0-pre node_modules/benchmark
    +-- platform@1.3.0
    +-- lodash-compat@3.10.0
    myndzi@test:~$ node
    > require('benchmark')
    { [Function: Benchmark]
      runInContext: [Function: runInContext],
      Benchmark: [Circular] }
    > require('benchmark').Suite
    undefined
    >

**Comment by jdalton** [comment]
Ya not sure what's up with that, the unit tests pass though.

**Comment by myndzi** [comment]
The test modifies global state (adds `QUnit` and `_`); when `_` is not added, the exports are broken.
